import { 
    TrendingUp, 
    TrendingDown,
    Users, 
    Briefcase, 
    PieChart, 
    Target, 
    Clock, 
    Brain, 
    Edit, 
    Search, 
    Code, 
    BarChart, 
    Lightbulb, 
    Cog,
    Layers,
    CheckCircle,
    Link,
    Link2,
    Database,
    Cloud,
    Cpu,
    Network,
    Shield,
    Zap,
    Globe,
    Calendar,
    FileText,
    Settings,
    Activity,
    Award,
    BookOpen,
    Camera,
    Download,
    Upload,
    Heart,
    Home,
    Info,
    Mail,
    MapPin,
    Phone,
    Play,
    Star,
    Truck,
    User,
    Video,
    Wifi,
    X,
    Check,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    Plus,
    Minus,
    Eye,
    EyeOff,
    Lock,
    Unlock,
    Folder,
    File,
    Image,
    Music,
    Headphones,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Server,
    HardDrive,
    Bluetooth,
    Battery,
    Power,
    Volume2,
    VolumeX,
    Mic,
    MicOff,
    Speaker,
    Radio,
    Tv,
    Gamepad2,
    Printer,
    Mouse,
    Keyboard,
    Webcam,
    Router,
    Usb,
    MemoryStick,
    Disc,
    Save,
    Share,
    Copy,
    Undo,
    Redo,
    RotateCcw,
    RotateCw,
    Maximize,
    Minimize,
    Move,
    Crop,
    Filter,
    Palette,
    Brush,
    Pencil,
    Pen,
    Type,
    Bold,
    Italic,
    Underline,
    AlignLeft,
    AlignCenter,
    AlignRight,
    List,
    Grid,
    Columns,
    Rows,
    Table,
    DollarSign,
    Euro,
    Percent,
    Calculator,
    PlusCircle,
    MinusCircle,
    XCircle,
    AlertCircle,
    AlertTriangle,
    HelpCircle,
    MessageCircle,
    MessageSquare,
    Send,
    Inbox,
    Paperclip,
    Flag,
    Bookmark,
    Tag,
    Archive,
    Trash,
    Delete,
    ShoppingCart,
    ShoppingBag,
    CreditCard,
    Banknote,
    Receipt,
    Package,
    Gift,
    Ticket,
    BarChart2,
    BarChart3,
    LineChart,
    Radar,
    Compass,
    Navigation,
    Map,
    Route,
    Car,
    Bus,
    Train,
    Plane,
    Ship,
    Bike,
    Timer,
    CalendarDays,
    CalendarCheck,
    CalendarX,
    CalendarPlus,
    Sun,
    Moon,
    CloudRain,
    CloudSnow,
    Wind,
    Thermometer,
    Droplets,
    Flame,
    Snowflake,
    Umbrella,
    Trees,
    Flower,
    Leaf,
    Sprout,
    Bug,
    Fish,
    Bird,
    Cat,
    Dog,
    Apple,
    Coffee,
    Cookie,
    Pizza,
    IceCream,
    Cake,
    Utensils,
    ChefHat,
    Wine,
    Beer,
    Milk
  } from "lucide-react";
  
  export const iconMap = {
    // Trending & Analytics
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'bar-chart': BarChart,
    'bar-chart-2': BarChart2,
    'bar-chart-3': BarChart3,
    'line-chart': LineChart,
    'pie-chart': PieChart,
    'activity': Activity,
    'radar': Radar,
    
    // People & Organization
    'users': Users,
    'user': User,
    'briefcase': Briefcase,
    'award': Award,
    'target': Target,
    'heart': Heart,
    
    // Technology & Computing
    'brain': Brain,
    'cpu': Cpu,
    'code': Code,
    'cog': Cog,
    'settings': Settings,
    'zap': Zap,
    'lightbulb': Lightbulb,
    'robot': Cog, // Using Cog as robot fallback
    'monitor': Monitor,
    'laptop': Laptop,
    'smartphone': Smartphone,
    'tablet': Tablet,
    'server': Server,
    'database': Database,
    'hard-drive': HardDrive,
    'network': Network,
    'wifi': Wifi,
    'bluetooth': Bluetooth,
    'router': Router,
    
    // Data & Storage
    'layers': Layers,
    'cloud': Cloud,
    'folder': Folder,
    'file': File,
    'file-text': FileText,
    'image': Image,
    'save': Save,
    'download': Download,
    'upload': Upload,
    'archive': Archive,
    'backup': Archive,
    
    // Connectivity & Links
    'link': Link,
    'link-2': Link2,
    'globe': Globe,
    'share': Share,
    'send': Send,
    'mail': Mail,
    'phone': Phone,
    'message-circle': MessageCircle,
    'message-square': MessageSquare,
    
    // Time & Scheduling
    'clock': Clock,
    'timer': Timer,
    'calendar': Calendar,
    'calendar-days': CalendarDays,
    'calendar-check': CalendarCheck,
    'calendar-x': CalendarX,
    'calendar-plus': CalendarPlus,
    
    // Actions & Controls
    'edit': Edit,
    'search': Search,
    'play': Play,
    'eye': Eye,
    'eye-off': EyeOff,
    'check': Check,
    'check-circle': CheckCircle,
    'x': X,
    'x-circle': XCircle,
    'plus': Plus,
    'plus-circle': PlusCircle,
    'minus': Minus,
    'minus-circle': MinusCircle,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'arrow-left': ArrowLeft,
    'arrow-right': ArrowRight,
    'chevron-up': ChevronUp,
    'chevron-down': ChevronDown,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'rotate-ccw': RotateCcw,
    'rotate-cw': RotateCw,
    
    // Security & Privacy
    'shield': Shield,
    'lock': Lock,
    'unlock': Unlock,
    'key': Lock, // Using Lock as key fallback
    
    // Media & Entertainment
    'camera': Camera,
    'video': Video,
    'music': Music,
    'headphones': Headphones,
    'volume-2': Volume2,
    'volume-x': VolumeX,
    'mic': Mic,
    'mic-off': MicOff,
    'speaker': Speaker,
    'radio': Radio,
    'tv': Tv,
    'gamepad': Gamepad2,
    
    // Navigation & Location
    'map': Map,
    'map-pin': MapPin,
    'compass': Compass,
    'navigation': Navigation,
    'route': Route,
    'home': Home,
    
    // Transportation
    'car': Car,
    'bus': Bus,
    'train': Train,
    'plane': Plane,
    'ship': Ship,
    'bike': Bike,
    'truck': Truck,

    
    // Commerce & Finance
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    'credit-card': CreditCard,
    'dollar-sign': DollarSign,
    'euro': Euro,
    'banknote': Banknote,
    'receipt': Receipt,
    'package': Package,
    'gift': Gift,
    'ticket': Ticket,
    'calculator': Calculator,
    'percent': Percent,
    
    // Content & Design
    'book-open': BookOpen,
    'palette': Palette,
    'brush': Brush,
    'pencil': Pencil,
    'pen': Pen,
    'type': Type,
    'bold': Bold,
    'italic': Italic,
    'underline': Underline,
    'align-left': AlignLeft,
    'align-center': AlignCenter,
    'align-right': AlignRight,
    'list': List,
    'grid': Grid,
    'table': Table,
    'columns': Columns,
    'rows': Rows,
    
    // Status & Alerts
    'info': Info,
    'alert-circle': AlertCircle,
    'alert-triangle': AlertTriangle,
    'help-circle': HelpCircle,
    'flag': Flag,
    'bookmark': Bookmark,
    'tag': Tag,
    'star': Star,
    
    // Weather & Environment
    'sun': Sun,
    'moon': Moon,
    'cloud-rain': CloudRain,
    'cloud-snow': CloudSnow,
    'wind': Wind,
    'thermometer': Thermometer,
    'droplets': Droplets,
    'flame': Flame,
    'snowflake': Snowflake,
    'umbrella': Umbrella,
    
    // Nature & Biology
    'trees': Trees,
    'flower': Flower,
    'leaf': Leaf,
    'sprout': Sprout,
    'bug': Bug,
    'fish': Fish,
    'bird': Bird,
    'cat': Cat,
    'dog': Dog,
    
    // Food & Nutrition
    'apple': Apple,
    'coffee': Coffee,
    'utensils': Utensils,
    'chef-hat': ChefHat,
    'wine': Wine,
    'beer': Beer,
    'milk': Milk,
    'cookie': Cookie,
    'pizza': Pizza,
    'ice-cream': IceCream,
    'cake': Cake,
    
    // Hardware & Peripherals
    'printer': Printer,
    'mouse': Mouse,
    'keyboard': Keyboard,
    'webcam': Webcam,
    'usb': Usb,
    'memory-stick': MemoryStick,
    'disc': Disc,
    'battery': Battery,
    'power': Power,
    
    // Organization & Productivity
    'inbox': Inbox,
    'paperclip': Paperclip,
    'copy': Copy,
    'undo': Undo,
    'redo': Redo,
    'trash': Trash,
    'delete': Delete,
    'maximize': Maximize,
    'minimize': Minimize,
    'move': Move,
    'crop': Crop,
    'filter': Filter
  };
  
  // Icon fallbacks for canvas rendering
  export const iconFallbacks = {
    // Trending & Analytics
    'trending-up': '📈',
    'trending-down': '📉',
    'trending-flat': '➡️',
    'bar-chart': '📊',
    'bar-chart-2': '📊',
    'bar-chart-3': '📊',
    'line-chart': '📈',
    'pie-chart': '🥧',
    'activity': '📊',
    'radar': '📡',
    
    // People & Organization
    'users': '👥',
    'user': '👤',
    'briefcase': '💼',
    'award': '🏆',
    'target': '🎯',
    'heart': '❤️',
    
    // Technology & Computing
    'brain': '🧠',
    'cpu': '💻',
    'code': '💻',
    'cog': '⚙️',
    'settings': '⚙️',
    'tool': '🔧',
    'zap': '⚡',
    'lightbulb': '💡',
    'robot': '🤖',
    'monitor': '🖥️',
    'laptop': '💻',
    'smartphone': '📱',
    'tablet': '📱',
    'server': '🖥️',
    'database': '🗄️',
    'hard-drive': '💾',
    'network': '🌐',
    'wifi': '📶',
    'bluetooth': '📡',
    'router': '📡',
    'ethernet': '🔌',
    
    // Data & Storage
    'layers': '📚',
    'cloud': '☁️',
    'folder': '📁',
    'file': '📄',
    'file-text': '📄',
    'image': '🖼️',
    'save': '💾',
    'download': '⬇️',
    'upload': '⬆️',
    'archive': '📦',
    'backup': '💾',
    
    // Connectivity & Links
    'link': '🔗',
    'link-2': '🔗',
    'globe': '🌍',
    'share': '📤',
    'send': '📤',
    'mail': '📧',
    'phone': '📞',
    'message-circle': '💬',
    'message-square': '💬',
    
    // Time & Scheduling
    'clock': '🕐',
    'timer': '⏰',
    'stopwatch': '⏱️',
    'alarm': '⏰',
    'calendar': '📅',
    'calendar-days': '📅',
    'calendar-check': '✅',
    'calendar-x': '❌',
    'calendar-plus': '➕',
    'schedule': '📅',
    
    // Actions & Controls
    'edit': '✏️',
    'search': '🔍',
    'play': '▶️',
    'eye': '👁️',
    'eye-off': '🙈',
    'check': '✅',
    'check-circle': '✅',
    'x': '❌',
    'x-circle': '❌',
    'plus': '➕',
    'plus-circle': '➕',
    'minus': '➖',
    'minus-circle': '➖',
    'arrow-up': '⬆️',
    'arrow-down': '⬇️',
    'arrow-left': '⬅️',
    'arrow-right': '➡️',
    'chevron-up': '🔼',
    'chevron-down': '🔽',
    'chevron-left': '◀️',
    'chevron-right': '▶️',
    'refresh': '🔄',
    'rotate-ccw': '↪️',
    'rotate-cw': '↩️',
    
    // Security & Privacy
    'shield': '🛡️',
    'lock': '🔒',
    'unlock': '🔓',
    'key': '🔑',
    
    // Media & Entertainment
    'camera': '📷',
    'video': '🎥',
    'music': '🎵',
    'headphones': '🎧',
    'volume-2': '🔊',
    'volume-x': '🔇',
    'mic': '🎤',
    'mic-off': '🔇',
    'speaker': '🔊',
    'radio': '📻',
    'tv': '📺',
    'gamepad': '🎮',
    
    // Navigation & Location
    'map': '🗺️',
    'map-pin': '📍',
    'compass': '🧭',
    'navigation': '🧭',
    'route': '🛣️',
    'home': '🏠',
    
    // Transportation
    'car': '🚗',
    'bus': '🚌',
    'train': '🚂',
    'plane': '✈️',
    'ship': '🚢',
    'bike': '🚲',
    'truck': '🚛',
    'walk': '🚶',
    
    // Commerce & Finance
    'shopping-cart': '🛒',
    'shopping-bag': '🛍️',
    'credit-card': '💳',
    'dollar-sign': '💰',
    'euro': '💶',
    'banknote': '💵',
    'receipt': '🧾',
    'package': '📦',
    'gift': '🎁',
    'ticket': '🎫',
    'calculator': '🧮',
    'percent': '%',
    
    // Content & Design
    'book-open': '📖',
    'palette': '🎨',
    'brush': '🖌️',
    'pencil': '✏️',
    'pen': '🖊️',
    'type': '📝',
    'bold': 'B',
    'italic': 'I',
    'underline': 'U',
    'align-left': '⬅️',
    'align-center': '⬇️',
    'align-right': '➡️',
    'list': '📋',
    'grid': '⌗',
    'table': '📋',
    'columns': '📋',
    'rows': '📋',
    
    // Status & Alerts
    'info': 'ℹ️',
    'alert-circle': '⚠️',
    'alert-triangle': '⚠️',
    'help-circle': '❓',
    'flag': '🚩',
    'bookmark': '🔖',
    'tag': '🏷️',
    'star': '⭐',
    
    // Weather & Environment
    'sun': '☀️',
    'moon': '🌙',
    'cloud-rain': '🌧️',
    'cloud-snow': '🌨️',
    'wind': '💨',
    'thermometer': '🌡️',
    'droplets': '💧',
    'flame': '🔥',
    'snowflake': '❄️',
    'umbrella': '☂️',
    
    // Nature & Biology
    'trees': '🌳',
    'flower': '🌸',
    'leaf': '🍃',
    'sprout': '🌱',
    'bug': '🐛',
    'fish': '🐟',
    'bird': '🐦',
    'cat': '🐱',
    'dog': '🐶',
    
    // Food & Nutrition
    'apple': '🍎',
    'coffee': '☕',
    'utensils': '🍴',
    'chef-hat': '👨‍🍳',
    'wine': '🍷',
    'beer': '🍺',
    'milk': '🥛',
    'cookie': '🍪',
    'pizza': '🍕',
    'ice-cream': '🍦',
    'cake': '🎂',
    
    // Hardware & Peripherals
    'printer': '🖨️',
    'scanner': '📠',
    'mouse': '🖱️',
    'keyboard': '⌨️',
    'webcam': '📹',
    'usb': '🔌',
    'sd-card': '💾',
    'memory-stick': '💾',
    'disc': '💿',
    'battery': '🔋',
    'power': '🔌',
    
    // Organization & Productivity
    'inbox': '📥',
    'paperclip': '📎',
    'copy': '📋',
    'cut': '✂️',
    'paste': '📋',
    'undo': '↶',
    'redo': '↷',
    'trash': '🗑️',
    'delete': '🗑️',
    'restore': '↶',
    'maximize': '⬜',
    'minimize': '🔻',
    'move': '↔️',
    'resize': '↔️',
    'crop': '✂️',
    'filter': '🔍'
  };
  
  // Get icon component with fallback
  export function getIcon(iconName: string) {
    return iconMap[iconName as keyof typeof iconMap] || TrendingUp;
  }
  
  // Get icon fallback emoji
  export function getIconFallback(iconName: string) {
    return iconFallbacks[iconName as keyof typeof iconFallbacks] || '📊';
  }